export FOX_VIRTUAL_AB_DEVICE=1
export OF_AB_DEVICE_WITH_RECOVERY_PARTITION=1
export OF_FL_PATH1="/tmp/flashlight"
export OF_ADVANCED_SECURITY=1

#Screen Settings 
export OF_SCREEN_H=2460
export OF_STATUS_H=100
export OF_STATUS_INDENT_LEFT=50
export OF_STATUS_INDENT_RIGHT=48

export OF_USE_GREEN_LED=0
export OF_CLOCK_POS=1
export OF_ALLOW_DISABLE_NAVBAR=0
export OF_ENABLE_LPTOOLS=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1

export OF_QUICK_BACKUP_LIST="/boot"
export OF_DEFAULT_TIMEZONE="IST-5:30"  
export FOX_USE_DATA_RECOVERY_FOR_SETTINGS=1
export FOX_DELETE_AROMAFM=1
export OF_MAINTAINER="ADITHYAN"

export ALLOW_MISSING_DEPENDENCIES=true
